ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE';
CREATE TABLE Achievement
  (
	ACHID INTEGER NOT NULL ,
    ACHNAME VARCHAR2 (60) NOT NULL ,
    ACHCOND VARCHAR2 (4000) NOT NULL 
  ) ;
ALTER TABLE Achievement ADD CONSTRAINT Achievement_PK PRIMARY KEY ( ACHID ) ;


CREATE TABLE Active
  (
    ACTID  INTEGER NOT NULL ,
    ACTUSER VARCHAR2(30) NOT NULL
  ) ;
ALTER TABLE Active ADD CONSTRAINT Active_PK PRIMARY KEY ( ACTID ) ;


CREATE TABLE Administrator
  ( UNAME VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Administrator ADD CONSTRAINT Administrator_PK PRIMARY KEY ( UNAME ) ;

CREATE TABLE AGE
  ( AGE VARCHAR2 (20) NOT NULL
  ) ;


CREATE TABLE Befriends
  (
    Game_User_UNAME  VARCHAR2 (30) NOT NULL ,
    Game_User_UNAME1 VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Befriends ADD CONSTRAINT Befriends_PK PRIMARY KEY ( Game_User_UNAME, Game_User_UNAME1 ) ;


CREATE TABLE Develops
  (
    Game_GAMEID         INTEGER NOT NULL ,
    Game_Developer_GDID INTEGER NOT NULL
  ) ;
ALTER TABLE Develops ADD CONSTRAINT Develops_PK PRIMARY KEY ( Game_GAMEID, Game_Developer_GDID ) ;


CREATE TABLE Develops_Request
  (
    Request_REQID         INTEGER NOT NULL ,
    Game_Developer_GDID INTEGER NOT NULL
  ) ;
ALTER TABLE Develops_Request ADD CONSTRAINT Develops_Request_PK PRIMARY KEY ( Request_REQID, Game_Developer_GDID ) ;


CREATE TABLE Earned
  (
    Game_User_UNAME     VARCHAR2 (30) NOT NULL ,
	EARNDATE DATE DEFAULT SYSDATE ,
	EARNTIME TIMESTAMP DEFAULT SYSTIMESTAMP ,
	ACHIEVEMENT_ACHID INTEGER NOT NULL
  ) ;
ALTER TABLE Earned ADD CONSTRAINT Earned_PK PRIMARY KEY ( ACHIEVEMENT_ACHID, GAME_USER_UNAME ) ;


CREATE TABLE FRIEND_REQUEST
 (
	FRID    INTEGER NOT NULL,
	SENDER  VARCHAR2 (30) NOT NULL,
	RECEIVER VARCHAR2(30) NOT NULL,
	REQDATE DATE DEFAULT SYSDATE,
	FRSTAT VARCHAR2(30) DEFAULT 'PENDING'
 
 );
ALTER TABLE FRIEND_REQUEST ADD CONSTRAINT FRIEND_REQUEST_PK PRIMARY KEY (FRID);
ALTER TABLE FRIEND_REQUEST add CONSTRAINT FRIENDS_UNIQUE UNIQUE (SENDER, RECEIVER);
ALTER TABLE FRIEND_REQUEST add CONSTRAINT CHECK_STATUS CHECK (FRSTAT IN ('PENDING', 'ACCEPTED', 'DECLINED'));


 CREATE TABLE FRIENDS_IN_GAME
 (
    GAMEID  INTEGER,
	GAMENAME      VARCHAR2(100),
    GAMERY INTEGER,
    UNAME VARCHAR2(30),
	UAVAT VARCHAR2(200)
 
 );


CREATE TABLE Game
  (
    GAMEID   INTEGER NOT NULL ,
    GAMENAME VARCHAR2 (100) NOT NULL ,
    GAMEDESC VARCHAR2(4000) DEFAULT 'N/A' ,
    GAMEPC INTEGER DEFAULT 0 ,
    GAMERY INTEGER NOT NULL ,
    GAMEDR VARCHAR2(2000) NOT NULL ,
    GAMEPSEC  INTEGER DEFAULT 0 ,
    GAMEPMIN  INTEGER DEFAULT 0 ,
    GAMEPHOUR  INTEGER DEFAULT 0 ,
    GAMEPDAY INTEGER DEFAULT 0 ,
	GAMEPN INTEGER DEFAULT 0 ,
	GIMG VARCHAR2(200) ,
	GAMEICON VARCHAR2(200) DEFAULT '../../icons/default.jpg'
  ) ;
ALTER TABLE Game ADD CONSTRAINT Game_PK PRIMARY KEY ( GAMEID ) ;
create unique index GAMEYEARUNIQUE on GAME( lower(GAMENAME), GAMERY ) ;


CREATE TABLE Game_Developer
  (
    GDNAME  VARCHAR2 (50) NOT NULL ,
    GDID    INTEGER NOT NULL ,
    GDCOUNT INTEGER
  ) ;
ALTER TABLE Game_Developer ADD CONSTRAINT Game_Developer_PK PRIMARY KEY ( GDID ) ;
ALTER TABLE GAME_DEVELOPER ADD CONSTRAINT GDNAME_UNIQUE UNIQUE (GDNAME) ;


CREATE TABLE Game_User
  (
    UNAME    VARCHAR2 (30) NOT NULL ,
    RNAME    VARCHAR2 (50) ,
    UCOUNTRY VARCHAR2 (50) NOT NULL ,
    UBIO VARCHAR2(4000) DEFAULT 'N/A',
    UDOB DATE NOT NULL ,
	PLAYING_GAME_ID INTEGER DEFAULT NULL ,
	PLAYING INTEGER DEFAULT 0
  ) ;
ALTER TABLE GAME_USER ADD CHECK ( UCOUNTRY IN ('Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo DR', 'Congo Republic', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea DPR', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands',
'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'São Tomé and Príncipe', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe')) ;
ALTER TABLE Game_User ADD CONSTRAINT Game_User_PK PRIMARY KEY ( UNAME ) ;
ALTER TABLE GAME_USER add CONSTRAINT CHECK_PLAYING CHECK (PLAYING IN (0,1));


CREATE TABLE Game_Group
  (
    GRID   INTEGER NOT NULL ,
    GRNAME VARCHAR2 (50) NOT NULL ,
    GRGM   VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Game_Group ADD CONSTRAINT Group_PK PRIMARY KEY ( GRID, GRGM ) ;
ALTER TABLE Game_Group ADD CONSTRAINT UNIQUE_ID UNIQUE (GRID);


CREATE TABLE Game_Genre
  (
    GAME_GAMEID INTEGER,
    GENRE_GNRID INTEGER
  ) ;
ALTER TABLE Game_Genre ADD CONSTRAINT GameGenre_PK PRIMARY KEY ( GAME_GAMEID, GENRE_GNRID ) ;


CREATE TABLE Genre
  (
    GNRNAME VARCHAR2(50),
    GNRID INTEGER
  ) ;
ALTER TABLE Genre ADD CONSTRAINT Genre_PK PRIMARY KEY ( GNRID ) ;
ALTER TABLE GENRE ADD CONSTRAINT UQ_Name UNIQUE (GNRNAME) ;


CREATE TABLE GROUP_INVITE
 (
	GIID      INTEGER NOT NULL,
	GROUP_ID  INTEGER NOT NULL ,
    GROUP_MASTER VARCHAR2(30) NOT NULL,
	GIREC VARCHAR2(30) NOT NULL,
	GIDATE DATE DEFAULT SYSDATE,
	GISTAT VARCHAR2(30) DEFAULT 'PENDING',
	CONSTRAINT CHECK_GISTAT_STATUS CHECK (GISTAT IN ('PENDING', 'ACCEPTED', 'DECLINED'))
 
 );
 
ALTER TABLE GROUP_INVITE ADD CONSTRAINT GROUP_INVITE_PK PRIMARY KEY (GIID);


CREATE TABLE GT_User
  (
    UNAME  VARCHAR2 (30) NOT NULL ,
    PWORD  VARCHAR2 (30) NOT NULL ,
    UDATE  DATE DEFAULT SYSDATE ,
    USERUT INTEGER DEFAULT 1 NOT NULL ,
    UEMAIL VARCHAR2 (30) NOT NULL ,
    UAVAT VARCHAR2(200)
  ) ;
ALTER TABLE GT_User ADD CONSTRAINT CHECK_UT CHECK ( USERUT IN (0, 1)) ;
ALTER TABLE GT_User ADD CONSTRAINT User_PK PRIMARY KEY ( UNAME ) ;


CREATE TABLE Guide
  (
    GUID INTEGER NOT NULL ,
    GUCONT VARCHAR2(4000) NOT NULL ,
    GUNAME          VARCHAR2 (200) NOT NULL ,
    Game_GAMEID     INTEGER NOT NULL ,
    Game_User_UNAME VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Guide ADD CONSTRAINT Guide_PK PRIMARY KEY ( GUID, Game_GAMEID, Game_User_UNAME ) ;


CREATE TABLE Item
  (
    ITEMID          INTEGER NOT NULL ,
    ITEMNAME        VARCHAR2 (100) NOT NULL ,
    ITEMPRICE       NUMBER (38,2) NOT NULL ,
    ITEMCURR        VARCHAR2 (20) NOT NULL ,
    Game_User_UNAME VARCHAR2 (30) NOT NULL ,
    ITEMIM VARCHAR2(200) NOT NULL ,
	GAME_GAMEID INTEGER ,
	ITEMQ INTEGER DEFAULT 1 ,
	ITEMSTAT VARCHAR2(30) DEFAULT 'IN STOCK' ,
	ITEMBUY VARCHAR2(30)
  ) ;
ALTER TABLE Item ADD CONSTRAINT Item_PK PRIMARY KEY ( ITEMID, Game_User_UNAME ) ;
ALTER TABLE Item ADD CONSTRAINT CHECK_CURR CHECK ( ITEMCURR IN ('AUS', 'CHF', 'EUR', 'GBP', 'RSD', 'USD', 'YEN')) ;
ALTER TABLE ITEM ADD CONSTRAINT CHECK_STAT CHECK (ITEMSTAT IN ('IN STOCK', 'SOLD', 'FINALIZED')) ;
ALTER TABLE ITEM add CONSTRAINT CHECK_QUANTITY_MAX CHECK (ITEMQ < 20);
ALTER TABLE ITEM add CONSTRAINT CHECK_QUANTITY CHECK (ITEMQ > 0);


CREATE TABLE MESSAGE
  (
    MSGDATE DATE DEFAULT SYSDATE ,
    MSGSENT VARCHAR2 (30) NOT NULL ,
    MSGCONT VARCHAR2 (4000) NOT NULL ,
	MSGTIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
  ) ;
ALTER TABLE MESSAGE ADD CONSTRAINT Message_PK PRIMARY KEY ( MSGSENT, MSGDATE, MSGTIME ) ;


CREATE TABLE Participating_In
  (
    Group_GRID      INTEGER NOT NULL ,
    Game_User_UNAME VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Participating_In ADD CONSTRAINT Participating_In_PK PRIMARY KEY ( Group_GRID, Game_User_UNAME ) ;


CREATE TABLE Played_Game
  (
    GAMEID     INTEGER NOT NULL ,
    GAMENAME   VARCHAR2(100) NOT NULL,
    GAMERY     NUMBER(*,0) NOT NULL,
	PTSEC NUMBER(*,0) DEFAULT 0, 
	PTMIN NUMBER(*,0) DEFAULT 0, 
	PTHOUR NUMBER(*,0) DEFAULT 0, 
	PTDAY NUMBER(*,0) DEFAULT 0,
    GIMAGE VARCHAR2(200),
    RANKNAME VARCHAR2 (50) DEFAULT 'Unranked'
  ) ;


CREATE TABLE Player
  (
    USERNAME VARCHAR2 (30) NOT NULL ,
    GAME     INTEGER NOT NULL ,
	PTSEC NUMBER(*,0) DEFAULT 0, 
	PTMIN NUMBER(*,0) DEFAULT 0, 
	PTHOUR NUMBER(*,0) DEFAULT 0, 
	PTDAY NUMBER(*,0) DEFAULT 0 ,
	AVATAR BLOB
  ) ;

CREATE TABLE Plays
  (
    Game_User_UNAME VARCHAR2 (30) NOT NULL ,
    Game_GAMEID     INTEGER NOT NULL ,
	PTSEC NUMBER(*,0) DEFAULT 0, 
	PTMIN NUMBER(*,0) DEFAULT 0, 
	PTHOUR NUMBER(*,0) DEFAULT 0, 
	PTDAY NUMBER(*,0) DEFAULT 0, 
	PLAYDATE DATE DEFAULT SYSDATE, 
	PTIME TIMESTAMP (6) DEFAULT SYSTIMESTAMP
  ) ;
ALTER TABLE Plays ADD CONSTRAINT Plays_PK PRIMARY KEY ( Game_User_UNAME, Game_GAMEID, PLAYDATE, PTIME ) ;


CREATE TABLE Post
  (
    POSTDATE DATE NOT NULL ,
    POSTPB   VARCHAR2 (30) NOT NULL ,
    POSTTID Integer ,
    POSTCONT CLOB NOT NULL ,
	POSTTIME TIMESTAMP DEFAULT SYSTIMESTAMP
  ) ;
ALTER TABLE Post ADD CONSTRAINT Post_PK PRIMARY KEY ( POSTPB, POSTTID, POSTDATE, POSTTIME ) ;


CREATE TABLE Rank
  (
	RANKNAME VARCHAR2 (50) NOT NULL , 
	RANKH INTEGER NOT NULL ,
	RANKID INTEGER NOT NULL
  ) ;
ALTER TABLE Rank ADD CONSTRAINT Rank_PK PRIMARY KEY ( RANKID ) ;
ALTER TABLE RANK ADD CONSTRAINT UNIQUE_RANK_NAME UNIQUE (RANKNAME) ;


CREATE TABLE Ranks
  (
    Game_GAMEID   INTEGER NOT NULL ,
	GAME_USER_UNAME VARCHAR2(30) ,
	RANKDATE DATE DEFAULT SYSDATE ,
	RANKTIME TIMESTAMP DEFAULT SYSTIMESTAMP ,
	RANK_RANKID INTEGER NOT NULL
  ) ;
ALTER TABLE Ranks ADD CONSTRAINT Ranks_PK PRIMARY KEY ( RANK_RANKID, GAME_GAMEID, GAME_USER_UNAME ) ;


CREATE TABLE Received
  (
    Message_MSGSENT VARCHAR2 (30) NOT NULL ,
	Message_MSGDATE DATE NOT NULL ,
	Message_MSGTIME TIMESTAMP NOT NULL ,
    User_UNAME      VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Received ADD CONSTRAINT Received_PK PRIMARY KEY ( Message_MSGSENT, Message_MSGDATE, Message_MSGTIME, User_UNAME ) ;


CREATE TABLE Request
  (
    REQID       INTEGER NOT NULL ,
    REQGNAME    VARCHAR2 (100) NOT NULL ,
    REQGRD      INTEGER NOT NULL ,
    REQSUB      VARCHAR2 (30) NOT NULL ,
    REQAPP      VARCHAR2 (30) ,
    Game_GAMEID INTEGER ,
    REQDESC VARCHAR2(4000) ,
    REQIMG VARCHAR2(200) ,
    REQDR VARCHAR2(2000) ,
	REQSTATUS VARCHAR2(50) DEFAULT 'PENDING'
  ) ;
ALTER TABLE Request ADD CONSTRAINT Request_PK PRIMARY KEY ( REQID ) ;
ALTER TABLE REQUEST ADD CONSTRAINT CHECK_REQ_STAT CHECK (REQSTATUS IN ('PENDING', 'DECLINED', 'ACCEPTED'));


CREATE TABLE Review
  (
    REVCONT VARCHAR2(4000) NOT NULL ,
    REVID       INTEGER NOT NULL ,
	REVTITLE VARCHAR2(100) NOT NULL ,
    Game_GAMEID INTEGER NOT NULL ,
    User_UNAME  VARCHAR2 (30) NOT NULL ,
    REVGRADE    INTEGER ,
	REVDATE DATE DEFAULT SYSDATE
  ) ;
ALTER TABLE Review ADD CHECK ( REVGRADE IN (0, 1, 2, 3, 4, 5)) ;
ALTER TABLE Review ADD CONSTRAINT Review_PK PRIMARY KEY ( REVID, Game_GAMEID, User_UNAME ) ;


CREATE TABLE Streamer
  (
	STRID INTEGER NOT NULL ,
    STRNAME VARCHAR2 (50) NOT NULL ,
    STRURL VARCHAR2(100) NOT NULL 
  ) ;
ALTER TABLE Streamer ADD CONSTRAINT Streamer_PK PRIMARY KEY ( STRID ) ;
ALTER TABLE STREAMER ADD CONSTRAINT UNIQUE_STREAMER_NAME UNIQUE (STRNAME) ;
create unique index UNIQUENAMEANDURL on STREAMER( STRNAME, STRURL ) ;


CREATE TABLE Streams
  (
    STREAMER_STRID INTEGER NOT NULL ,
    Game_GAMEID INTEGER NOT NULL
  ) ;
ALTER TABLE Streams ADD CONSTRAINT Streams_PK PRIMARY KEY ( Game_GAMEID, Streamer_STRID ) ;


CREATE TABLE TICKET
 (
	TICKID      INTEGER NOT NULL,
	TICKT  VARCHAR2(100) NOT NULL ,
    TICKDESC VARCHAR2(4000) NOT NULL,
	TICKSTAT VARCHAR2(30) DEFAULT 'SUBMITED',
    TICKSUB VARCHAR2(30),
	CONSTRAINT CHECK_TICKSTAT_STATUS CHECK (TICKSTAT IN ('SUBMITTED', 'ANSWERED'))
 );
ALTER TABLE TICKET ADD CONSTRAINT TICKET_PK PRIMARY KEY (TICKID);


CREATE TABLE TICKET_ANSWER
 (
	TANSID      INTEGER NOT NULL,
    TANSCONT VARCHAR2(4000) NOT NULL,
    TANSTICK INTEGER NOT NULL,
	TANSRESP VARCHAR2(30) NOT NULL
 );
ALTER TABLE TICKET_ANSWER ADD CONSTRAINT TICKET_ANSWER_PK PRIMARY KEY (TANSID);


CREATE TABLE Topic
  (
	TPID INTEGER NOT NULL ,
    TPTITLE VARCHAR2 (100) NOT NULL ,
    TPPC    INTEGER NOT NULL ,
    TPOD    DATE NOT NULL ,
    TPLMD   DATE NOT NULL ,
    TOPOP   VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Topic ADD CONSTRAINT Topic_PK PRIMARY KEY ( TPID ) ;


CREATE TABLE Token
  (
    TOKID  INTEGER NOT NULL ,
    TOKEN VARCHAR2 (300) NOT NULL,
    TOKEXP DATE NOT NULL,
    TOKEM VARCHAR2(30) NOT NULL,
    TOKPW VARCHAR2(30) NOT NULL,
    TOKUN VARCHAR2(30) NOT NULL,
    TOKAVAT VARCHAR2(4000),
    TOKBIO VARCHAR2(4000),
    TOKDOB VARCHAR2(30) NOT NULL,
    TOKRN VARCHAR2(50),
    TOKCNTRY VARCHAR2(50) NOT NULL
  ) ;
ALTER TABLE Token ADD CONSTRAINT Token_PK PRIMARY KEY ( TOKID ) ;
  
  
CREATE TABLE Top_Game
  (
    GAMEID     INTEGER NOT NULL ,
    GAMENAME   VARCHAR2(100) NOT NULL,
    GAMERY     NUMBER(*,0) NOT NULL,
	PTSEC NUMBER(*,0) DEFAULT 0, 
	PTMIN NUMBER(*,0) DEFAULT 0, 
	PTHOUR NUMBER(*,0) DEFAULT 0, 
	PTDAY NUMBER(*,0) DEFAULT 0,
    GIMAGE VARCHAR2(200)
  ) ;


ALTER TABLE Active ADD CONSTRAINT Active_GTUSER_FK FOREIGN KEY ( ACTUSER ) REFERENCES GT_USER ( UNAME ) ;

ALTER TABLE Administrator ADD CONSTRAINT Administrator_User_FK FOREIGN KEY ( UNAME ) REFERENCES GT_User ( UNAME ) ;

ALTER TABLE Earned ADD CONSTRAINT Earmed_User_FK FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Earned ADD CONSTRAINT Earned_Achiev_FK FOREIGN KEY ( Achievement_ACHID ) REFERENCES Achievement ( ACHID ) ;

ALTER TABLE Plays ADD CONSTRAINT Plays_User_FK FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Plays ADD CONSTRAINT Plays_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Ranks ADD CONSTRAINT Ranks_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Ranks ADD CONSTRAINT RANKS_USER FOREIGN KEY ( GAME_USER_UNAME ) REFERENCES Game_USER ( UNAME ) ;

ALTER TABLE Ranks ADD CONSTRAINT Ranks_ID_FK FOREIGN KEY ( Rank_RANKID ) REFERENCES Rank ( RANKID ) ;

ALTER TABLE Received ADD CONSTRAINT Rec_User_FK FOREIGN KEY ( User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Received ADD CONSTRAINT Rec_Message_FK FOREIGN KEY ( Message_MSGSENT, Message_MSGDATE, Message_MSGTIME ) REFERENCES MESSAGE ( MSGSENT, MSGDATE, MSGTIME ) ;

ALTER TABLE Streams ADD CONSTRAINT Streams_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Streams ADD CONSTRAINT Streames_Streamer_FK FOREIGN KEY ( Streamer_STRID ) REFERENCES Streamer ( STRID ) ;

ALTER TABLE Befriends ADD CONSTRAINT Game_User_Name FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Befriends ADD CONSTRAINT Game_User_Name1 FOREIGN KEY ( Game_User_UNAME1 ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Develops ADD CONSTRAINT Develops_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Develops ADD CONSTRAINT Develops_Developer_FK FOREIGN KEY ( Game_Developer_GDID ) REFERENCES Game_Developer ( GDID ) ;

ALTER TABLE Develops_Request ADD CONSTRAINT DEVELOPS_REQUEST_FK_REQUEST FOREIGN KEY ( Request_REQID ) REFERENCES Request ( REQID ) ;

ALTER TABLE Develops_Request ADD CONSTRAINT DEVELOPS_REQUEST_FK_DEVELOPER FOREIGN KEY ( Game_Developer_GDID ) REFERENCES Game_Developer ( GDID ) ;

ALTER TABLE FRIEND_REQUEST ADD CONSTRAINT FRIEND_REQUEST_USER1 FOREIGN KEY ( SENDER ) REFERENCES GAME_USER ( UNAME ) ;
 
ALTER TABLE FRIEND_REQUEST ADD CONSTRAINT FRIEND_REQUEST_USER2 FOREIGN KEY ( RECEIVER ) REFERENCES GAME_USER ( UNAME ) ;

ALTER TABLE Game_Genre ADD CONSTRAINT FK_Genre_Game_Genre FOREIGN KEY (GENRE_GNRID) REFERENCES GENRE (GNRID);

ALTER TABLE Game_Genre ADD CONSTRAINT FK_Game_Game_Genre FOREIGN KEY (GAME_GAMEID) REFERENCES GAME (GAMEID);

ALTER TABLE GAME_Group ADD CONSTRAINT Group_User_FK FOREIGN KEY ( GRGM ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Game_User ADD CONSTRAINT Game_User_User_FK FOREIGN KEY ( UNAME ) REFERENCES GT_User ( UNAME ) ;

ALTER TABLE GAME_USER ADD CONSTRAINT FK_PLAYING_GAME FOREIGN KEY (PLAYING_GAME_ID) REFERENCES GAME (GAMEID);

ALTER TABLE Guide ADD CONSTRAINT Guide_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Guide ADD CONSTRAINT Guide_Game_User_FK FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE GROUP_INVITE ADD CONSTRAINT GROUP_INVITE_USER FOREIGN KEY ( GIREC ) REFERENCES GAME_USER ( UNAME ) ;

ALTER TABLE GROUP_INVITE ADD CONSTRAINT GROUP_INVITE_GROUP FOREIGN KEY ( GROUP_ID, GROUP_MASTER ) REFERENCES GAME_GROUP ( GRID, GRGM ) ;

ALTER TABLE Item ADD CONSTRAINT Item_Game_User_FK FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE ITEM ADD CONSTRAINT FK_GAME FOREIGN KEY (GAME_GAMEID) REFERENCES GAME (GAMEID);

ALTER TABLE ITEM ADD CONSTRAINT BUYER_FK FOREIGN KEY (ITEMBUY) REFERENCES GAME_USER(UNAME);

ALTER TABLE MESSAGE ADD CONSTRAINT Message_User_FK FOREIGN KEY ( MSGSENT ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Participating_In ADD CONSTRAINT Particip_Group_FK FOREIGN KEY ( Group_GRID ) REFERENCES Game_Group ( GRID ) ;

ALTER TABLE Participating_In ADD CONSTRAINT Particip_User_FK FOREIGN KEY ( Game_User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Post ADD CONSTRAINT Post_Topic_FK FOREIGN KEY ( POSTTID ) REFERENCES Topic ( TPID ) ;

ALTER TABLE Post ADD CONSTRAINT Post_User_FK FOREIGN KEY ( POSTPB ) REFERENCES GT_User ( UNAME ) ;

ALTER TABLE Request ADD CONSTRAINT Request_Administrator_FK FOREIGN KEY ( REQAPP ) REFERENCES Administrator ( UNAME ) ;

ALTER TABLE Request ADD CONSTRAINT Request_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Request ADD CONSTRAINT Request_Game_User_FK FOREIGN KEY ( REQSUB ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE Review ADD CONSTRAINT Review_Game_FK FOREIGN KEY ( Game_GAMEID ) REFERENCES Game ( GAMEID ) ;

ALTER TABLE Review ADD CONSTRAINT Review_User_FK FOREIGN KEY ( User_UNAME ) REFERENCES Game_User ( UNAME ) ;

ALTER TABLE TICKET ADD CONSTRAINT FK_TICKET_SUBMITER FOREIGN KEY (TICKSUB) REFERENCES GAME_USER (UNAME);

ALTER TABLE TICKET_ANSWER ADD CONSTRAINT FK_TICKET_ANSWER_ADMIN FOREIGN KEY (TANSRESP) REFERENCES ADMINISTRATOR (UNAME);

ALTER TABLE TICKET_ANSWER ADD CONSTRAINT FK_TICKET_ANSWER_TICKET FOREIGN KEY (TANSTICK) REFERENCES TICKET (TICKID);

ALTER TABLE Topic ADD CONSTRAINT Topic_User_FK FOREIGN KEY ( TOPOP ) REFERENCES GT_User ( UNAME ) ;

  /
 CREATE SEQUENCE game_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE guide_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE developer_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE review_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE group_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE request_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE item_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE ach_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE rank_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE stream_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE topic_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE token_seq
 START WITH     1
 INCREMENT BY   1
 MAXVALUE 99999999999999999999999
 NOCACHE
 CYCLE;
 /
 CREATE SEQUENCE active_seq
 START WITH     1
 INCREMENT BY   1
 MAXVALUE 99999999999999999999999
 NOCACHE
 CYCLE;
 /
  CREATE SEQUENCE friend_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
  CREATE SEQUENCE grinvite_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE ticket_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE;
 /
 CREATE SEQUENCE answer_seq
  START WITH     1
  INCREMENT BY   1
  NOCACHE;
 /
  CREATE SEQUENCE genre_seq
  START WITH     1
  INCREMENT BY   1
  NOCACHE;
 /
